### ISSUE TITLE
"No matching records found" on Windows Phone

### ISSUE THREAD

**Issue by kkokosa** [callForPapers/callForPapers.github.io#19] opened 2015-11-18 10:36 UTC
There is a bug causing "No matching records found" displayed instead of data on Windows Phone.

**Comment by cmatskas** [comment] 2015-11-18 10:42
Lol, did you say Windows Phone? I'll try and have a look, though I can't promise I'll find the solution. Do you get a stack trace?

**Comment by cmatskas** [comment] 2015-11-18 11:54
It works fine on my WP -> OS 10 insider preview (fast ring) with the latest update.Still failing for you?

**Comment by kkokosa** [comment] 2015-11-18 20:46
Still the same - WP 8.1 here. Unfortunately do not have time today to look into details...

**Comment by Gutek** [comment] 2015-11-20 13:38
so just in case i will +1 here, as it does not work for me too.

**Comment by cmatskas** [comment] 2015-11-20 13:40
Have we assigned this to anyone yet? I may be able to look at this at some point next week but I'll need to figure out how and if that's even possible ?? Suggestions?

**Comment by cmatskas** [comment] 2015-11-20 13:44
Right, I can replicate this in IE when running under Windows phone emulation. Making some progress...

**Comment by cmatskas** [comment] 2015-11-20 14:11
I think I'm able to recreate this by running the site locally in IIS and serving the pages like they are on the site. The problem is with the actual call to `./data/cfp_generated.json?sort=callForPapersEnd&order=asc` which is used to populate the bootstrap datatable. Rather than getting the compiled file, IIS serves the raw file, which is more or less what the Windows phone does. 

So, when I look the contents of the `cfp_generate.json` instead of json data, i get the code used to generate the data, i.e. 

```
---
readme: to add new confernce put a JSON file in _data/conferences folder
layout: null
---
{
  "events" : [  
    {% for cfp in site.data.conferences %}
      {{cfp[1] | jsonify}}
      {% if forloop.rindex0 > 0 %},{% endif %}
    {% endfor %}
  ]
}
```

The only problem with this is that I don't recognize the syntax/language. Any ideas on how to fix this are more than welcome /cc @kkokosa @mihcall

**Comment by kkokosa** [comment] 2015-11-20 14:16
I believe localhost testing will require using [Jekyll](https://jekyllrb.com/), which was used by @ptrstpp950

**Comment by ptrstpp950** [comment] 2015-11-20 14:26
It is exactly a Jekyll. To install it you will need ruby and follow instructions from official site. When I get home I will try to recreate this bug.

**Comment by Gutek** [comment] 2015-11-20 14:30
its working now...

**Comment by Gutek** [comment] 2015-11-20 14:31
imo its require.js issue... try opening for the first time - table is empty, try again (not refresh on mobile!), it works

**Comment by witchy-mutant** [comment] 2015-11-20 14:34
@gutek Is it not showing records on the first load? You have to open it again every time?

**Comment by Gutek** [comment] 2015-11-20 14:34
ok, its a fix by @mihcall  :) and it does what it needs to do :) grats :+1:

**Comment by witchy-mutant** [comment] 2015-11-20 14:34
:green_heart:

**Comment by Gutek** [comment] 2015-11-20 14:35
@mihcall now even with cache cleaning it works every-time on desktop IE :) and it loads on WP so, that ql :)

**Comment by witchy-mutant** [comment] 2015-11-20 14:35
That makes me happy :)

**Closed as completed by witchy-mutant** 2015-11-20 14:35 UTC
Labels: bug

**Comment by cmatskas** [comment] 2015-11-20 14:36
:+1: :green_heart: 
Job well done @mihcall

**Comment by Gutek** [comment] 2015-11-20 14:41
@mihcall take a look at my comments on commit, any questions shout :)

**Comment by ptrstpp950** [comment] 2015-11-20 16:37
@Gutek ☺
